/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32_F103C6_GPIO_Driver.h"




void clock_init ()
{
	/* Enable clock GPIOA */
	RCC_GPIOA_CLK_EN();
	/* Enable clock GPIOB  Bit 3 IOPBEN: I/O port B clock enable */
	RCC_GPIOB_CLK_EN();
}
void GPIO_init ()
{
	GPIO_PinConfig_t Pincfg;

	/* PA1 floating input */
	Pincfg.GPIO_PinNumber = GPIO_PIN_1;
	Pincfg.GPIO_MODE=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &Pincfg);

	/*PB1 output push_pull*/
	Pincfg.GPIO_PinNumber = GPIO_PIN_1;
	Pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	Pincfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &Pincfg);

	/* PA13 floating input */
	Pincfg.GPIO_PinNumber = GPIO_PIN_13;
	Pincfg.GPIO_MODE=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &Pincfg);

	/*PB13 output push_pull*/
	Pincfg.GPIO_PinNumber = GPIO_PIN_13;
	Pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	Pincfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &Pincfg);
}
void wait_ms (uint32_t time)
{
	uint32_t i , j;
	for (i=0;i<time;i++)
		for(j=0;j<255;j++);
}
int main(void)
{
	clock_init ();
	GPIO_init ();


	while (1)
	{
		/* PA1 connected ==> PUR  */
		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0)  /* press */
		{
			MCAL_GPIO_togglePin(GPIOA, GPIO_PIN_1);
			while (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0);
		}

		/* PA13 connected ==> PDR  */
		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1)  /* press */
		{
			MCAL_GPIO_togglePin(GPIOA, GPIO_PIN_13);

		}
		wait_ms(1);
	}
}

